# Generated by Django 4.2.8 on 2024-01-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_rating_booking_review_delete_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='review',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
